In [1]:
import pandas as pd

In [4]:
path = "/Users/maximerichard/dev/personal/finance_code/dfkhelper/lib/hero_score/stats_by_hero/"
path_primary = path + "primary.csv"
path_secondary = path + "secondary.csv"

primary = pd.read_csv(path_primary)
secondary = pd.read_csv(path_secondary)

In [6]:
primary

,hero,strength,wisdom,intelligence,vitality,luck,dexterity,endurance,agility
0,Warrior,75.0,20.0,20.0,65.0,35.0,70.0,65.0,50.0
1,Knight,70.0,25.0,20.0,75.0,35.0,55.0,75.0,45.0
2,Thief,55.0,35.0,25.0,50.0,65.0,55.0,45.0,70.0
3,Archer,55.0,25.0,40.0,50.0,40.0,80.0,60.0,50.0
4,Priest,30.0,80.0,70.0,50.0,40.0,30.0,60.0,40.0
5,Wizard,30.0,80.0,80.0,50.0,40.0,30.0,50.0,40.0
6,Monk,60.0,50.0,25.0,60.0,30.0,60.0,55.0,60.0
7,Pirate,70.0,20.0,20.0,60.0,55.0,70.0,55.0,50.0
8,Berserker,80.0,20.0,20.0,65.0,40.0,60.0,60.0,55.0
9,Seer,30.0,80.0,70.0,50.0,35.0,30.0,50.0,55.0
10,Paladin *,80.0,65.0,30.0,80.0,40.0,40.0,80.0,35.0
11,Dark Knight *,85.0,35.0,70.0,75.0,35.0,55.0,60.0,35.0
12,Summoner *,45.0,85.0,85.0,50.0,40.0,45.0,50.0,50.0
13,Ninja *,50.0,40.0,50.0,50.0,60.0,75.0,40.0,85.0
14,Shapeshifter *,65.0,45.0,25.0,55.0,45.0,70.0,55.0,80.0
15,Dragoon **,80.0,60.0,50.0,60.0,50.0,65.0,70.0,65.0
16,Sage **,40.0,90.0,90.0,60.0,55.0,40.0,50.0,75.0
17,Dread Knight ***,85.0,65.0,65.0,65.0,60.0,75.0,75.0,60.0

In [ ]:
hero_class = "Warrior"

In [7]:
secondary

,stat,Knight,Thief,Archer,Priest,Wizard,Monk,Pirate,Berserker,Seer,Paladin *,Dark Knight *,Summoner *,Ninja *,Shapeshifter *,Dragoon **,Sage **,Dread Knight ***
0,wisdom,6.25,8.75,6.25,20.0,20.0,12.50,5.00,5.00,20.00,16.25,8.75,21.25,10.00,11.25,15.00,22.50,16.25
1,intelligence,5.00,6.25,10.00,17.5,20.0,6.25,5.00,5.00,17.50,7.50,17.50,21.25,12.50,6.25,12.50,22.50,16.25
2,vitality,18.75,12.50,12.50,12.5,12.5,15.00,15.00,16.25,12.50,20.00,18.75,12.50,12.50,13.75,15.00,15.00,16.25
3,luck,8.75,16.25,10.00,10.0,10.0,7.50,13.75,10.00,8.75,10.00,8.75,10.00,15.00,11.25,12.50,13.75,15.00
4,dexterity,13.75,13.75,20.00,7.5,7.5,15.00,17.50,15.00,7.50,10.00,13.75,11.25,18.75,17.50,16.25,10.00,18.75
5,endurance,18.75,11.25,15.00,15.0,12.5,13.75,13.75,15.00,12.50,20.00,15.00,12.50,10.00,13.75,17.50,12.50,18.75
6,agility,11.25,17.50,12.50,10.0,10.0,15.00,12.50,13.75,13.75,8.75,8.75,12.50,21.25,21.25,16.25,18.75,15.00